/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {6, 1, 0, 5, 0, 1, 2, 3,
  4};
static const casadi_int casadi_s1[27] = 
  {3, 6, 0, 3, 6, 9, 12, 15,
  18, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s2[45] = 
  {40, 6, 0, 6, 12, 18, 24, 30,
  36, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5};
static const casadi_int casadi_s3[163] = 
  {3, 40, 0, 3, 6, 9, 12, 15,
  18, 21, 24, 27, 30, 33, 36, 39,
  42, 45, 48, 51, 54, 57, 60, 63,
  66, 69, 72, 75, 78, 81, 84, 87,
  90, 93, 96, 99, 102, 105, 108, 111,
  114, 117, 120, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 0,
  1, 2, 0, 1, 2, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s4[7] = {6, 1, 0, 3, 1, 3, 5};
static const casadi_int casadi_s5[11] = 
  {3, 2, 0, 3, 6, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s6[7] = {40, 2, 0, 1, 2, 6, 7};
static const casadi_int casadi_s7[11] = 
  {6, 2, 0, 3, 6, 1, 3, 5,
  1, 3, 5};
static const casadi_int casadi_s8[15] = 
  {2, 6, 0, 0, 2, 2, 4, 4,
  6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s9[17] = 
  {40, 2, 0, 6, 12, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5};
static const casadi_int casadi_s10[3] = {6, 1, 1};
static const casadi_int casadi_s11[3] = {6, 6, 1};
static const casadi_int casadi_s12[3] = {6, 2, 1};
static const casadi_int casadi_s13[3] = {2, 1, 1};
static const casadi_int casadi_s14[3] = {1, 1, 1};

static const casadi_real casadi_zeros[36] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* External functions */
int jac_residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* residual_quadrotor2D:(i0[1x40])->(o0[1x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_residual_quadrotor2D:(i0[1x40],out_o0[1x3,0nz])->(jac_o0_i0[3x40]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* quadrotor2D_learned_expl_vde_forw:(i0[6],i1[6x6],i2[6x2],i3[2],i4)->(o0[6],o1[6x6],o2[6x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, *w14=w+17, w15, w16, w17, w18, w19, w20, w21;
  casadi_real w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33;
  casadi_real w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45;
  casadi_real *w46=w+54, *w47=w+94, *w48=w+97, *w49=w+103, *w50=w+139, *w51=w+145, *w52=w+151, *w53=w+157, *w55=w+163, *w56=w+168, *w58=w+186, *w59=w+306;
  casadi_real *w60=w+312, *w61=w+315, *w62=w+318, *w63=w+321, *w64=w+324, *w65=w+327, *w66=w+329, *w67=w+341;
  const casadi_real **arg1=arg+5, *cs, *wr14, *wr48, *wr49, *wr50, *wr51, *wr52, *wr53, *wr67;
  /* #0: @0 = input[0][1] */
  w00 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[0][4] */
  w01 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = sin(@1) */
  w02 = sin( w01 );
  /* #3: @3 = input[3][0] */
  w03 = arg[3] ? arg[3][0] : 0;
  /* #4: @4 = input[3][1] */
  w04 = arg[3] ? arg[3][1] : 0;
  /* #5: @5 = (@3+@4) */
  w05  = (w03+w04);
  /* #6: @6 = (@2*@5) */
  w06  = (w02*w05);
  /* #7: @7 = 0.027 */
  w07 = 2.7000000000000000e-02;
  /* #8: @6 = (@6/@7) */
  w06 /= w07;
  /* #9: @8 = input[0][3] */
  w08 = arg[0] ? arg[0][3] : 0;
  /* #10: @9 = cos(@1) */
  w09 = cos( w01 );
  /* #11: @10 = (@9*@5) */
  w10  = (w09*w05);
  /* #12: @10 = (@10/@7) */
  w10 /= w07;
  /* #13: @7 = 9.8 */
  w07 = 9.8000000000000007e+00;
  /* #14: @10 = (@10-@7) */
  w10 -= w07;
  /* #15: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #16: @11 = 0.0397 */
  w11 = 3.9699999999999999e-02;
  /* #17: @12 = (@4-@3) */
  w12  = (w04-w03);
  /* #18: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #19: @13 = 1.4e-05 */
  w13 = 1.4000000000000000e-05;
  /* #20: @12 = (@12/@13) */
  w12 /= w13;
  /* #21: @13 = 1.41421 */
  w13 = 1.4142135623730951e+00;
  /* #22: @12 = (@12/@13) */
  w12 /= w13;
  /* #23: @14 = vertcat(@0, @6, @8, @10, @7, @12) */
  rr=w14;
  *rr++ = w00;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w12;
  /* #24: @6 = 0 */
  w06 = 0.;
  /* #25: @10 = input[0][0] */
  w10 = arg[0] ? arg[0][0] : 0;
  /* #26: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #27: @13 = 3.14159 */
  w13 = 3.1415926535897931e+00;
  /* #28: @15 = input[4][0] */
  w15 = arg[4] ? arg[4][0] : 0;
  /* #29: @13 = (@13*@15) */
  w13 *= w15;
  /* #30: @16 = sin(@13) */
  w16 = sin( w13 );
  /* #31: @17 = 1.5708 */
  w17 = 1.5707963267948966e+00;
  /* #32: @17 = (@17*@15) */
  w17 *= w15;
  /* #33: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #34: @19 = 1.0472 */
  w19 = 1.0471975511965976e+00;
  /* #35: @19 = (@19*@15) */
  w19 *= w15;
  /* #36: @20 = sin(@19) */
  w20 = sin( w19 );
  /* #37: @21 = 0.785398 */
  w21 = 7.8539816339744828e-01;
  /* #38: @21 = (@21*@15) */
  w21 *= w15;
  /* #39: @22 = sin(@21) */
  w22 = sin( w21 );
  /* #40: @23 = 0.628319 */
  w23 = 6.2831853071795862e-01;
  /* #41: @23 = (@23*@15) */
  w23 *= w15;
  /* #42: @24 = sin(@23) */
  w24 = sin( w23 );
  /* #43: @25 = 0.523599 */
  w25 = 5.2359877559829882e-01;
  /* #44: @25 = (@25*@15) */
  w25 *= w15;
  /* #45: @26 = sin(@25) */
  w26 = sin( w25 );
  /* #46: @27 = 0.448799 */
  w27 = 4.4879895051282759e-01;
  /* #47: @27 = (@27*@15) */
  w27 *= w15;
  /* #48: @28 = sin(@27) */
  w28 = sin( w27 );
  /* #49: @29 = 0.392699 */
  w29 = 3.9269908169872414e-01;
  /* #50: @29 = (@29*@15) */
  w29 *= w15;
  /* #51: @30 = sin(@29) */
  w30 = sin( w29 );
  /* #52: @31 = 0.349066 */
  w31 = 3.4906585039886590e-01;
  /* #53: @31 = (@31*@15) */
  w31 *= w15;
  /* #54: @32 = sin(@31) */
  w32 = sin( w31 );
  /* #55: @33 = 0.314159 */
  w33 = 3.1415926535897931e-01;
  /* #56: @33 = (@33*@15) */
  w33 *= w15;
  /* #57: @34 = sin(@33) */
  w34 = sin( w33 );
  /* #58: @35 = 0.285599 */
  w35 = 2.8559933214452665e-01;
  /* #59: @35 = (@35*@15) */
  w35 *= w15;
  /* #60: @36 = sin(@35) */
  w36 = sin( w35 );
  /* #61: @37 = 0.261799 */
  w37 = 2.6179938779914941e-01;
  /* #62: @37 = (@37*@15) */
  w37 *= w15;
  /* #63: @38 = sin(@37) */
  w38 = sin( w37 );
  /* #64: @39 = 0.241661 */
  w39 = 2.4166097335306100e-01;
  /* #65: @39 = (@39*@15) */
  w39 *= w15;
  /* #66: @40 = sin(@39) */
  w40 = sin( w39 );
  /* #67: @41 = 0.224399 */
  w41 = 2.2439947525641379e-01;
  /* #68: @41 = (@41*@15) */
  w41 *= w15;
  /* #69: @42 = sin(@41) */
  w42 = sin( w41 );
  /* #70: @43 = 0.20944 */
  w43 = 2.0943951023931953e-01;
  /* #71: @43 = (@43*@15) */
  w43 *= w15;
  /* #72: @44 = sin(@43) */
  w44 = sin( w43 );
  /* #73: @45 = 0.19635 */
  w45 = 1.9634954084936207e-01;
  /* #74: @45 = (@45*@15) */
  w45 *= w15;
  /* #75: @15 = sin(@45) */
  w15 = sin( w45 );
  /* #76: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #77: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #78: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #79: @21 = cos(@21) */
  w21 = cos( w21 );
  /* #80: @23 = cos(@23) */
  w23 = cos( w23 );
  /* #81: @25 = cos(@25) */
  w25 = cos( w25 );
  /* #82: @27 = cos(@27) */
  w27 = cos( w27 );
  /* #83: @29 = cos(@29) */
  w29 = cos( w29 );
  /* #84: @31 = cos(@31) */
  w31 = cos( w31 );
  /* #85: @33 = cos(@33) */
  w33 = cos( w33 );
  /* #86: @35 = cos(@35) */
  w35 = cos( w35 );
  /* #87: @37 = cos(@37) */
  w37 = cos( w37 );
  /* #88: @39 = cos(@39) */
  w39 = cos( w39 );
  /* #89: @41 = cos(@41) */
  w41 = cos( w41 );
  /* #90: @43 = cos(@43) */
  w43 = cos( w43 );
  /* #91: @45 = cos(@45) */
  w45 = cos( w45 );
  /* #92: @46 = vertcat(@10, @0, @12, @8, @1, @7, @3, @4, @16, @18, @20, @22, @24, @26, @28, @30, @32, @34, @36, @38, @40, @42, @44, @15, @13, @17, @19, @21, @23, @25, @27, @29, @31, @33, @35, @37, @39, @41, @43, @45) */
  rr=w46;
  *rr++ = w10;
  *rr++ = w00;
  *rr++ = w12;
  *rr++ = w08;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w42;
  *rr++ = w44;
  *rr++ = w15;
  *rr++ = w13;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w23;
  *rr++ = w25;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w33;
  *rr++ = w35;
  *rr++ = w37;
  *rr++ = w39;
  *rr++ = w41;
  *rr++ = w43;
  *rr++ = w45;
  /* #93: @46 = @46' */
  /* #94: @47 = residual_quadrotor2D(@46) */
  arg1[0]=w46;
  res1[0]=w47;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #95: @47 = @47' */
  /* #96: @10 = @47[0] */
  for (rr=(&w10), cs=w47+0; cs!=w47+1; cs+=1) *rr++ = *cs;
  /* #97: @0 = @47[1] */
  for (rr=(&w00), cs=w47+1; cs!=w47+2; cs+=1) *rr++ = *cs;
  /* #98: @12 = @47[2] */
  for (rr=(&w12), cs=w47+2; cs!=w47+3; cs+=1) *rr++ = *cs;
  /* #99: @48 = vertcat(@6, @10, @6, @0, @6, @12) */
  rr=w48;
  *rr++ = w06;
  *rr++ = w10;
  *rr++ = w06;
  *rr++ = w00;
  *rr++ = w06;
  *rr++ = w12;
  /* #100: @14 = (@14+@48) */
  for (i=0, rr=w14, cs=w48; i<6; ++i) (*rr++) += (*cs++);
  /* #101: output[0][0] = @14 */
  casadi_copy(w14, 6, res[0]);
  /* #102: @49 = input[1][0] */
  wr49 = arg[1] ? arg[1] : casadi_zeros;
  /* #103: {@14, @48, @50, @51, @52, @53} = horzsplit(@49) */
  wr14 = wr49;
  wr48 = wr49+6;
  wr50 = wr49+12;
  wr51 = wr49+18;
  wr52 = wr49+24;
  wr53 = wr49+30;
  /* #104: {@6, @10, @0, @12, @8, @1} = vertsplit(@14) */
  w06 = wr14[0];
  w10 = wr14[1];
  w00 = wr14[2];
  w12 = wr14[3];
  w08 = wr14[4];
  w01 = wr14[5];
  /* #105: @7 = 37.037 */
  w07 = 3.7037037037037038e+01;
  /* #106: @3 = (@9*@8) */
  w03  = (w09*w08);
  /* #107: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #108: @3 = (@7*@3) */
  w03  = (w07*w03);
  /* #109: @4 = (@2*@8) */
  w04  = (w02*w08);
  /* #110: @4 = (@5*@4) */
  w04  = (w05*w04);
  /* #111: @4 = (@7*@4) */
  w04  = (w07*w04);
  /* #112: @4 = (-@4) */
  w04 = (- w04 );
  /* #113: @54 = 00 */
  /* #114: @55 = vertcat(@10, @3, @12, @4, @1, @54) */
  rr=w55;
  *rr++ = w10;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w04;
  *rr++ = w01;
  /* #115: @14 = dense(@55) */
  casadi_densify(w55, casadi_s0, w14, 0);
  /* #116: @56 = zeros(3x6) */
  casadi_clear(w56, 18);
  /* #117: @57 = zeros(1x3,0nz) */
  /* #118: @58 = jac_residual_quadrotor2D(@46, @57) */
  arg1[0]=w46;
  arg1[1]=0;
  res1[0]=w58;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #119: @59 = vertcat(@6, @10, @0, @12, @8, @1, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w59;
  *rr++ = w06;
  *rr++ = w10;
  *rr++ = w00;
  *rr++ = w12;
  *rr++ = w08;
  *rr++ = w01;
  /* #120: {@6, @10, @0, @12, @8, @1} = vertsplit(@48) */
  w06 = wr48[0];
  w10 = wr48[1];
  w00 = wr48[2];
  w12 = wr48[3];
  w08 = wr48[4];
  w01 = wr48[5];
  /* #121: @48 = vertcat(@6, @10, @0, @12, @8, @1, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w48;
  *rr++ = w06;
  *rr++ = w10;
  *rr++ = w00;
  *rr++ = w12;
  *rr++ = w08;
  *rr++ = w01;
  /* #122: {@6, @0, @3, @4, @16, @18} = vertsplit(@50) */
  w06 = wr50[0];
  w00 = wr50[1];
  w03 = wr50[2];
  w04 = wr50[3];
  w16 = wr50[4];
  w18 = wr50[5];
  /* #123: @50 = vertcat(@6, @0, @3, @4, @16, @18, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w50;
  *rr++ = w06;
  *rr++ = w00;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w16;
  *rr++ = w18;
  /* #124: {@6, @3, @20, @22, @24, @26} = vertsplit(@51) */
  w06 = wr51[0];
  w03 = wr51[1];
  w20 = wr51[2];
  w22 = wr51[3];
  w24 = wr51[4];
  w26 = wr51[5];
  /* #125: @51 = vertcat(@6, @3, @20, @22, @24, @26, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w51;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w24;
  *rr++ = w26;
  /* #126: {@6, @20, @28, @30, @32, @34} = vertsplit(@52) */
  w06 = wr52[0];
  w20 = wr52[1];
  w28 = wr52[2];
  w30 = wr52[3];
  w32 = wr52[4];
  w34 = wr52[5];
  /* #127: @52 = vertcat(@6, @20, @28, @30, @32, @34, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w52;
  *rr++ = w06;
  *rr++ = w20;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w34;
  /* #128: {@6, @28, @36, @38, @40, @42} = vertsplit(@53) */
  w06 = wr53[0];
  w28 = wr53[1];
  w36 = wr53[2];
  w38 = wr53[3];
  w40 = wr53[4];
  w42 = wr53[5];
  /* #129: @53 = vertcat(@6, @28, @36, @38, @40, @42, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w53;
  *rr++ = w06;
  *rr++ = w28;
  *rr++ = w36;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w42;
  /* #130: @49 = horzcat(@59, @48, @50, @51, @52, @53) */
  rr=w49;
  for (i=0, cs=w59; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<6; ++i) *rr++ = *cs++;
  /* #131: @56 = mac(@58,@49,@56) */
  casadi_mtimes(w58, casadi_s3, w49, casadi_s2, w56, casadi_s1, w, 0);
  /* #132: {@47, @60, @61, @62, @63, @64} = horzsplit(@56) */
  casadi_copy(w56, 3, w47);
  casadi_copy(w56+3, 3, w60);
  casadi_copy(w56+6, 3, w61);
  casadi_copy(w56+9, 3, w62);
  casadi_copy(w56+12, 3, w63);
  casadi_copy(w56+15, 3, w64);
  /* #133: @6 = @47[0] */
  for (rr=(&w06), cs=w47+0; cs!=w47+1; cs+=1) *rr++ = *cs;
  /* #134: @36 = @47[1] */
  for (rr=(&w36), cs=w47+1; cs!=w47+2; cs+=1) *rr++ = *cs;
  /* #135: @44 = @47[2] */
  for (rr=(&w44), cs=w47+2; cs!=w47+3; cs+=1) *rr++ = *cs;
  /* #136: @47 = vertcat(@54, @6, @54, @36, @54, @44) */
  rr=w47;
  *rr++ = w06;
  *rr++ = w36;
  *rr++ = w44;
  /* #137: @59 = dense(@47) */
  casadi_densify(w47, casadi_s4, w59, 0);
  /* #138: @14 = (@14+@59) */
  for (i=0, rr=w14, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #139: output[1][0] = @14 */
  casadi_copy(w14, 6, res[1]);
  /* #140: @6 = (@9*@8) */
  w06  = (w09*w08);
  /* #141: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #142: @6 = (@7*@6) */
  w06  = (w07*w06);
  /* #143: @8 = (@2*@8) */
  w08  = (w02*w08);
  /* #144: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #145: @8 = (@7*@8) */
  w08  = (w07*w08);
  /* #146: @8 = (-@8) */
  w08 = (- w08 );
  /* #147: @55 = vertcat(@10, @6, @12, @8, @1, @54) */
  rr=w55;
  *rr++ = w10;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w08;
  *rr++ = w01;
  /* #148: @14 = dense(@55) */
  casadi_densify(w55, casadi_s0, w14, 0);
  /* #149: @10 = @60[0] */
  for (rr=(&w10), cs=w60+0; cs!=w60+1; cs+=1) *rr++ = *cs;
  /* #150: @6 = @60[1] */
  for (rr=(&w06), cs=w60+1; cs!=w60+2; cs+=1) *rr++ = *cs;
  /* #151: @12 = @60[2] */
  for (rr=(&w12), cs=w60+2; cs!=w60+3; cs+=1) *rr++ = *cs;
  /* #152: @60 = vertcat(@54, @10, @54, @6, @54, @12) */
  rr=w60;
  *rr++ = w10;
  *rr++ = w06;
  *rr++ = w12;
  /* #153: @59 = dense(@60) */
  casadi_densify(w60, casadi_s4, w59, 0);
  /* #154: @14 = (@14+@59) */
  for (i=0, rr=w14, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #155: output[1][1] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+6);
  /* #156: @10 = (@9*@16) */
  w10  = (w09*w16);
  /* #157: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #158: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #159: @16 = (@2*@16) */
  w16  = (w02*w16);
  /* #160: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #161: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #162: @16 = (-@16) */
  w16 = (- w16 );
  /* #163: @55 = vertcat(@0, @10, @4, @16, @18, @54) */
  rr=w55;
  *rr++ = w00;
  *rr++ = w10;
  *rr++ = w04;
  *rr++ = w16;
  *rr++ = w18;
  /* #164: @14 = dense(@55) */
  casadi_densify(w55, casadi_s0, w14, 0);
  /* #165: @0 = @61[0] */
  for (rr=(&w00), cs=w61+0; cs!=w61+1; cs+=1) *rr++ = *cs;
  /* #166: @10 = @61[1] */
  for (rr=(&w10), cs=w61+1; cs!=w61+2; cs+=1) *rr++ = *cs;
  /* #167: @4 = @61[2] */
  for (rr=(&w04), cs=w61+2; cs!=w61+3; cs+=1) *rr++ = *cs;
  /* #168: @61 = vertcat(@54, @0, @54, @10, @54, @4) */
  rr=w61;
  *rr++ = w00;
  *rr++ = w10;
  *rr++ = w04;
  /* #169: @59 = dense(@61) */
  casadi_densify(w61, casadi_s4, w59, 0);
  /* #170: @14 = (@14+@59) */
  for (i=0, rr=w14, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #171: output[1][2] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+12);
  /* #172: @0 = (@9*@24) */
  w00  = (w09*w24);
  /* #173: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #174: @0 = (@7*@0) */
  w00  = (w07*w00);
  /* #175: @24 = (@2*@24) */
  w24  = (w02*w24);
  /* #176: @24 = (@5*@24) */
  w24  = (w05*w24);
  /* #177: @24 = (@7*@24) */
  w24  = (w07*w24);
  /* #178: @24 = (-@24) */
  w24 = (- w24 );
  /* #179: @55 = vertcat(@3, @0, @22, @24, @26, @54) */
  rr=w55;
  *rr++ = w03;
  *rr++ = w00;
  *rr++ = w22;
  *rr++ = w24;
  *rr++ = w26;
  /* #180: @14 = dense(@55) */
  casadi_densify(w55, casadi_s0, w14, 0);
  /* #181: @3 = @62[0] */
  for (rr=(&w03), cs=w62+0; cs!=w62+1; cs+=1) *rr++ = *cs;
  /* #182: @0 = @62[1] */
  for (rr=(&w00), cs=w62+1; cs!=w62+2; cs+=1) *rr++ = *cs;
  /* #183: @22 = @62[2] */
  for (rr=(&w22), cs=w62+2; cs!=w62+3; cs+=1) *rr++ = *cs;
  /* #184: @62 = vertcat(@54, @3, @54, @0, @54, @22) */
  rr=w62;
  *rr++ = w03;
  *rr++ = w00;
  *rr++ = w22;
  /* #185: @59 = dense(@62) */
  casadi_densify(w62, casadi_s4, w59, 0);
  /* #186: @14 = (@14+@59) */
  for (i=0, rr=w14, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #187: output[1][3] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+18);
  /* #188: @3 = (@9*@32) */
  w03  = (w09*w32);
  /* #189: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #190: @3 = (@7*@3) */
  w03  = (w07*w03);
  /* #191: @32 = (@2*@32) */
  w32  = (w02*w32);
  /* #192: @32 = (@5*@32) */
  w32  = (w05*w32);
  /* #193: @32 = (@7*@32) */
  w32  = (w07*w32);
  /* #194: @32 = (-@32) */
  w32 = (- w32 );
  /* #195: @55 = vertcat(@20, @3, @30, @32, @34, @54) */
  rr=w55;
  *rr++ = w20;
  *rr++ = w03;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w34;
  /* #196: @14 = dense(@55) */
  casadi_densify(w55, casadi_s0, w14, 0);
  /* #197: @20 = @63[0] */
  for (rr=(&w20), cs=w63+0; cs!=w63+1; cs+=1) *rr++ = *cs;
  /* #198: @3 = @63[1] */
  for (rr=(&w03), cs=w63+1; cs!=w63+2; cs+=1) *rr++ = *cs;
  /* #199: @30 = @63[2] */
  for (rr=(&w30), cs=w63+2; cs!=w63+3; cs+=1) *rr++ = *cs;
  /* #200: @63 = vertcat(@54, @20, @54, @3, @54, @30) */
  rr=w63;
  *rr++ = w20;
  *rr++ = w03;
  *rr++ = w30;
  /* #201: @59 = dense(@63) */
  casadi_densify(w63, casadi_s4, w59, 0);
  /* #202: @14 = (@14+@59) */
  for (i=0, rr=w14, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #203: output[1][4] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+24);
  /* #204: @20 = (@9*@40) */
  w20  = (w09*w40);
  /* #205: @20 = (@5*@20) */
  w20  = (w05*w20);
  /* #206: @20 = (@7*@20) */
  w20  = (w07*w20);
  /* #207: @40 = (@2*@40) */
  w40  = (w02*w40);
  /* #208: @40 = (@5*@40) */
  w40  = (w05*w40);
  /* #209: @40 = (@7*@40) */
  w40  = (w07*w40);
  /* #210: @40 = (-@40) */
  w40 = (- w40 );
  /* #211: @55 = vertcat(@28, @20, @38, @40, @42, @54) */
  rr=w55;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w42;
  /* #212: @14 = dense(@55) */
  casadi_densify(w55, casadi_s0, w14, 0);
  /* #213: @28 = @64[0] */
  for (rr=(&w28), cs=w64+0; cs!=w64+1; cs+=1) *rr++ = *cs;
  /* #214: @20 = @64[1] */
  for (rr=(&w20), cs=w64+1; cs!=w64+2; cs+=1) *rr++ = *cs;
  /* #215: @38 = @64[2] */
  for (rr=(&w38), cs=w64+2; cs!=w64+3; cs+=1) *rr++ = *cs;
  /* #216: @64 = vertcat(@54, @28, @54, @20, @54, @38) */
  rr=w64;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w38;
  /* #217: @59 = dense(@64) */
  casadi_densify(w64, casadi_s4, w59, 0);
  /* #218: @14 = (@14+@59) */
  for (i=0, rr=w14, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #219: output[1][5] = @14 */
  if (res[1]) casadi_copy(w14, 6, res[1]+30);
  /* #220: @14 = zeros(2x6,6nz) */
  casadi_clear(w14, 6);
  /* #221: @28 = ones(2x1,1nz) */
  w28 = 1.;
  /* #222: {@20, NULL} = vertsplit(@28) */
  w20 = w28;
  /* #223: @28 = (@2*@20) */
  w28  = (w02*w20);
  /* #224: @28 = (@7*@28) */
  w28  = (w07*w28);
  /* #225: @38 = (@9*@20) */
  w38  = (w09*w20);
  /* #226: @38 = (@7*@38) */
  w38  = (w07*w38);
  /* #227: @40 = 0.707107 */
  w40 = 7.0710678118654746e-01;
  /* #228: @42 = 71428.6 */
  w42 = 7.1428571428571435e+04;
  /* #229: @3 = (@11*@20) */
  w03  = (w11*w20);
  /* #230: @3 = (@42*@3) */
  w03  = (w42*w03);
  /* #231: @3 = (@40*@3) */
  w03  = (w40*w03);
  /* #232: @3 = (-@3) */
  w03 = (- w03 );
  /* #233: @64 = vertcat(@54, @28, @54, @38, @54, @3) */
  rr=w64;
  *rr++ = w28;
  *rr++ = w38;
  *rr++ = w03;
  /* #234: @59 = zeros(3x2) */
  casadi_clear(w59, 6);
  /* #235: @28 = vertcat(@54, @54, @54, @54, @54, @54, @20, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=(&w28);
  *rr++ = w20;
  /* #236: @20 = ones(2x1,1nz) */
  w20 = 1.;
  /* #237: {NULL, @38} = vertsplit(@20) */
  w38 = w20;
  /* #238: @20 = vertcat(@54, @54, @54, @54, @54, @54, @54, @38, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=(&w20);
  *rr++ = w38;
  /* #239: @65 = horzcat(@28, @20) */
  rr=w65;
  *rr++ = w28;
  *rr++ = w20;
  /* #240: @48 = mac(@58,@65,@59) */
  casadi_copy(w59, 6, w48);
  casadi_mtimes(w58, casadi_s3, w65, casadi_s6, w48, casadi_s5, w, 0);
  /* #241: {@63, @62} = horzsplit(@48) */
  casadi_copy(w48, 3, w63);
  casadi_copy(w48+3, 3, w62);
  /* #242: @28 = @63[0] */
  for (rr=(&w28), cs=w63+0; cs!=w63+1; cs+=1) *rr++ = *cs;
  /* #243: @20 = @63[1] */
  for (rr=(&w20), cs=w63+1; cs!=w63+2; cs+=1) *rr++ = *cs;
  /* #244: @3 = @63[2] */
  for (rr=(&w03), cs=w63+2; cs!=w63+3; cs+=1) *rr++ = *cs;
  /* #245: @63 = vertcat(@54, @28, @54, @20, @54, @3) */
  rr=w63;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w03;
  /* #246: @64 = (@64+@63) */
  for (i=0, rr=w64, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #247: @63 = @64[:3] */
  for (rr=w63, cs=w64+0; cs!=w64+3; cs+=1) *rr++ = *cs;
  /* #248: (@14[:6:2] = @63) */
  for (rr=w14+0, cs=w63; rr!=w14+6; rr+=2) *rr = *cs++;
  /* #249: @28 = (@2*@38) */
  w28  = (w02*w38);
  /* #250: @28 = (@7*@28) */
  w28  = (w07*w28);
  /* #251: @20 = (@9*@38) */
  w20  = (w09*w38);
  /* #252: @20 = (@7*@20) */
  w20  = (w07*w20);
  /* #253: @11 = (@11*@38) */
  w11 *= w38;
  /* #254: @42 = (@42*@11) */
  w42 *= w11;
  /* #255: @40 = (@40*@42) */
  w40 *= w42;
  /* #256: @63 = vertcat(@54, @28, @54, @20, @54, @40) */
  rr=w63;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w40;
  /* #257: @28 = @62[0] */
  for (rr=(&w28), cs=w62+0; cs!=w62+1; cs+=1) *rr++ = *cs;
  /* #258: @20 = @62[1] */
  for (rr=(&w20), cs=w62+1; cs!=w62+2; cs+=1) *rr++ = *cs;
  /* #259: @40 = @62[2] */
  for (rr=(&w40), cs=w62+2; cs!=w62+3; cs+=1) *rr++ = *cs;
  /* #260: @62 = vertcat(@54, @28, @54, @20, @54, @40) */
  rr=w62;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w40;
  /* #261: @63 = (@63+@62) */
  for (i=0, rr=w63, cs=w62; i<3; ++i) (*rr++) += (*cs++);
  /* #262: @62 = @63[:3] */
  for (rr=w62, cs=w63+0; cs!=w63+3; cs+=1) *rr++ = *cs;
  /* #263: (@14[1:7:2] = @62) */
  for (rr=w14+1, cs=w62; rr!=w14+7; rr+=2) *rr = *cs++;
  /* #264: @48 = @14' */
  casadi_trans(w14,casadi_s8, w48, casadi_s7, iw);
  /* #265: @66 = dense(@48) */
  casadi_densify(w48, casadi_s7, w66, 0);
  /* #266: @67 = input[2][0] */
  wr67 = arg[2] ? arg[2] : casadi_zeros;
  /* #267: {@48, @14} = horzsplit(@67) */
  wr48 = wr67;
  wr14 = wr67+6;
  /* #268: {@28, @20, @40, @42, @11, @38} = vertsplit(@48) */
  w28 = wr48[0];
  w20 = wr48[1];
  w40 = wr48[2];
  w42 = wr48[3];
  w11 = wr48[4];
  w38 = wr48[5];
  /* #269: @3 = (@9*@11) */
  w03  = (w09*w11);
  /* #270: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #271: @3 = (@7*@3) */
  w03  = (w07*w03);
  /* #272: @30 = (@2*@11) */
  w30  = (w02*w11);
  /* #273: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #274: @30 = (@7*@30) */
  w30  = (w07*w30);
  /* #275: @30 = (-@30) */
  w30 = (- w30 );
  /* #276: @55 = vertcat(@20, @3, @42, @30, @38, @54) */
  rr=w55;
  *rr++ = w20;
  *rr++ = w03;
  *rr++ = w42;
  *rr++ = w30;
  *rr++ = w38;
  /* #277: @48 = dense(@55) */
  casadi_densify(w55, casadi_s0, w48, 0);
  /* #278: @50 = vertcat(@28, @20, @40, @42, @11, @38, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w50;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w40;
  *rr++ = w42;
  *rr++ = w11;
  *rr++ = w38;
  /* #279: {@28, @20, @40, @42, @11, @38} = vertsplit(@14) */
  w28 = wr14[0];
  w20 = wr14[1];
  w40 = wr14[2];
  w42 = wr14[3];
  w11 = wr14[4];
  w38 = wr14[5];
  /* #280: @14 = vertcat(@28, @20, @40, @42, @11, @38, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54, @54) */
  rr=w14;
  *rr++ = w28;
  *rr++ = w20;
  *rr++ = w40;
  *rr++ = w42;
  *rr++ = w11;
  *rr++ = w38;
  /* #281: @67 = horzcat(@50, @14) */
  rr=w67;
  for (i=0, cs=w50; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<6; ++i) *rr++ = *cs++;
  /* #282: @59 = mac(@58,@67,@59) */
  casadi_mtimes(w58, casadi_s3, w67, casadi_s9, w59, casadi_s5, w, 0);
  /* #283: {@62, @63} = horzsplit(@59) */
  casadi_copy(w59, 3, w62);
  casadi_copy(w59+3, 3, w63);
  /* #284: @28 = @62[0] */
  for (rr=(&w28), cs=w62+0; cs!=w62+1; cs+=1) *rr++ = *cs;
  /* #285: @40 = @62[1] */
  for (rr=(&w40), cs=w62+1; cs!=w62+2; cs+=1) *rr++ = *cs;
  /* #286: @3 = @62[2] */
  for (rr=(&w03), cs=w62+2; cs!=w62+3; cs+=1) *rr++ = *cs;
  /* #287: @62 = vertcat(@54, @28, @54, @40, @54, @3) */
  rr=w62;
  *rr++ = w28;
  *rr++ = w40;
  *rr++ = w03;
  /* #288: @59 = dense(@62) */
  casadi_densify(w62, casadi_s4, w59, 0);
  /* #289: @48 = (@48+@59) */
  for (i=0, rr=w48, cs=w59; i<6; ++i) (*rr++) += (*cs++);
  /* #290: @9 = (@9*@11) */
  w09 *= w11;
  /* #291: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #292: @9 = (@7*@9) */
  w09  = (w07*w09);
  /* #293: @2 = (@2*@11) */
  w02 *= w11;
  /* #294: @5 = (@5*@2) */
  w05 *= w02;
  /* #295: @7 = (@7*@5) */
  w07 *= w05;
  /* #296: @7 = (-@7) */
  w07 = (- w07 );
  /* #297: @55 = vertcat(@20, @9, @42, @7, @38, @54) */
  rr=w55;
  *rr++ = w20;
  *rr++ = w09;
  *rr++ = w42;
  *rr++ = w07;
  *rr++ = w38;
  /* #298: @59 = dense(@55) */
  casadi_densify(w55, casadi_s0, w59, 0);
  /* #299: @20 = @63[0] */
  for (rr=(&w20), cs=w63+0; cs!=w63+1; cs+=1) *rr++ = *cs;
  /* #300: @9 = @63[1] */
  for (rr=(&w09), cs=w63+1; cs!=w63+2; cs+=1) *rr++ = *cs;
  /* #301: @42 = @63[2] */
  for (rr=(&w42), cs=w63+2; cs!=w63+3; cs+=1) *rr++ = *cs;
  /* #302: @63 = vertcat(@54, @20, @54, @9, @54, @42) */
  rr=w63;
  *rr++ = w20;
  *rr++ = w09;
  *rr++ = w42;
  /* #303: @50 = dense(@63) */
  casadi_densify(w63, casadi_s4, w50, 0);
  /* #304: @59 = (@59+@50) */
  for (i=0, rr=w59, cs=w50; i<6; ++i) (*rr++) += (*cs++);
  /* #305: @67 = horzcat(@48, @59) */
  rr=w67;
  for (i=0, cs=w48; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<6; ++i) *rr++ = *cs++;
  /* #306: @66 = (@66+@67) */
  for (i=0, rr=w66, cs=w67; i<12; ++i) (*rr++) += (*cs++);
  /* #307: output[2][0] = @66 */
  casadi_copy(w66, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    case 4: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 45;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 353;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 45*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 353*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
