/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor2D_learned_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};

/* External functions */
int adj1_residual_quadrotor2D(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* adj1_residual_quadrotor2D:(i0[1x40],out_o0[1x3,0nz],adj_o0[1x3])->(adj_i0[1x40]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (adj1_residual_quadrotor2D(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* quadrotor2D_learned_expl_vde_adj:(i0[6],i1[6],i2[2],i3)->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21;
  casadi_real w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33;
  casadi_real w34, w35, w36, w37, w38, w39, *w40=w+40, *w42=w+80, *w43=w+83, *w44=w+89;
  const casadi_real **arg1=arg+4, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w04 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[2][0] */
  w06 = arg[2] ? arg[2][0] : 0;
  /* #7: @7 = input[2][1] */
  w07 = arg[2] ? arg[2][1] : 0;
  /* #8: @8 = 3.14159 */
  w08 = 3.1415926535897931e+00;
  /* #9: @9 = input[3][0] */
  w09 = arg[3] ? arg[3][0] : 0;
  /* #10: @8 = (@8*@9) */
  w08 *= w09;
  /* #11: @10 = sin(@8) */
  w10 = sin( w08 );
  /* #12: @11 = 1.5708 */
  w11 = 1.5707963267948966e+00;
  /* #13: @11 = (@11*@9) */
  w11 *= w09;
  /* #14: @12 = sin(@11) */
  w12 = sin( w11 );
  /* #15: @13 = 1.0472 */
  w13 = 1.0471975511965976e+00;
  /* #16: @13 = (@13*@9) */
  w13 *= w09;
  /* #17: @14 = sin(@13) */
  w14 = sin( w13 );
  /* #18: @15 = 0.785398 */
  w15 = 7.8539816339744828e-01;
  /* #19: @15 = (@15*@9) */
  w15 *= w09;
  /* #20: @16 = sin(@15) */
  w16 = sin( w15 );
  /* #21: @17 = 0.628319 */
  w17 = 6.2831853071795862e-01;
  /* #22: @17 = (@17*@9) */
  w17 *= w09;
  /* #23: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #24: @19 = 0.523599 */
  w19 = 5.2359877559829882e-01;
  /* #25: @19 = (@19*@9) */
  w19 *= w09;
  /* #26: @20 = sin(@19) */
  w20 = sin( w19 );
  /* #27: @21 = 0.448799 */
  w21 = 4.4879895051282759e-01;
  /* #28: @21 = (@21*@9) */
  w21 *= w09;
  /* #29: @22 = sin(@21) */
  w22 = sin( w21 );
  /* #30: @23 = 0.392699 */
  w23 = 3.9269908169872414e-01;
  /* #31: @23 = (@23*@9) */
  w23 *= w09;
  /* #32: @24 = sin(@23) */
  w24 = sin( w23 );
  /* #33: @25 = 0.349066 */
  w25 = 3.4906585039886590e-01;
  /* #34: @25 = (@25*@9) */
  w25 *= w09;
  /* #35: @26 = sin(@25) */
  w26 = sin( w25 );
  /* #36: @27 = 0.314159 */
  w27 = 3.1415926535897931e-01;
  /* #37: @27 = (@27*@9) */
  w27 *= w09;
  /* #38: @28 = sin(@27) */
  w28 = sin( w27 );
  /* #39: @29 = 0.285599 */
  w29 = 2.8559933214452665e-01;
  /* #40: @29 = (@29*@9) */
  w29 *= w09;
  /* #41: @30 = sin(@29) */
  w30 = sin( w29 );
  /* #42: @31 = 0.261799 */
  w31 = 2.6179938779914941e-01;
  /* #43: @31 = (@31*@9) */
  w31 *= w09;
  /* #44: @32 = sin(@31) */
  w32 = sin( w31 );
  /* #45: @33 = 0.241661 */
  w33 = 2.4166097335306100e-01;
  /* #46: @33 = (@33*@9) */
  w33 *= w09;
  /* #47: @34 = sin(@33) */
  w34 = sin( w33 );
  /* #48: @35 = 0.224399 */
  w35 = 2.2439947525641379e-01;
  /* #49: @35 = (@35*@9) */
  w35 *= w09;
  /* #50: @36 = sin(@35) */
  w36 = sin( w35 );
  /* #51: @37 = 0.20944 */
  w37 = 2.0943951023931953e-01;
  /* #52: @37 = (@37*@9) */
  w37 *= w09;
  /* #53: @38 = sin(@37) */
  w38 = sin( w37 );
  /* #54: @39 = 0.19635 */
  w39 = 1.9634954084936207e-01;
  /* #55: @39 = (@39*@9) */
  w39 *= w09;
  /* #56: @9 = sin(@39) */
  w09 = sin( w39 );
  /* #57: @8 = cos(@8) */
  w08 = cos( w08 );
  /* #58: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #59: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #60: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #61: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #62: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #63: @21 = cos(@21) */
  w21 = cos( w21 );
  /* #64: @23 = cos(@23) */
  w23 = cos( w23 );
  /* #65: @25 = cos(@25) */
  w25 = cos( w25 );
  /* #66: @27 = cos(@27) */
  w27 = cos( w27 );
  /* #67: @29 = cos(@29) */
  w29 = cos( w29 );
  /* #68: @31 = cos(@31) */
  w31 = cos( w31 );
  /* #69: @33 = cos(@33) */
  w33 = cos( w33 );
  /* #70: @35 = cos(@35) */
  w35 = cos( w35 );
  /* #71: @37 = cos(@37) */
  w37 = cos( w37 );
  /* #72: @39 = cos(@39) */
  w39 = cos( w39 );
  /* #73: @40 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @10, @12, @14, @16, @18, @20, @22, @24, @26, @28, @30, @32, @34, @36, @38, @9, @8, @11, @13, @15, @17, @19, @21, @23, @25, @27, @29, @31, @33, @35, @37, @39) */
  rr=w40;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w38;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w23;
  *rr++ = w25;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w33;
  *rr++ = w35;
  *rr++ = w37;
  *rr++ = w39;
  /* #74: @40 = @40' */
  /* #75: @41 = zeros(1x3,0nz) */
  /* #76: @42 = zeros(3x1) */
  casadi_clear(w42, 3);
  /* #77: @43 = input[1][0] */
  casadi_copy(arg[1], 6, w43);
  /* #78: {@0, @1, @2, @3, @5, @10} = vertsplit(@43) */
  w00 = w43[0];
  w01 = w43[1];
  w02 = w43[2];
  w03 = w43[3];
  w05 = w43[4];
  w10 = w43[5];
  /* #79: (@42[2] += @10) */
  for (rr=w42+2, cs=(&w10); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #80: (@42[1] += @3) */
  for (rr=w42+1, cs=(&w03); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #81: (@42[0] += @1) */
  for (rr=w42+0, cs=(&w01); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #82: @42 = @42' */
  /* #83: @44 = adj1_residual_quadrotor2D(@40, @41, @42) */
  arg1[0]=w40;
  arg1[1]=0;
  arg1[2]=w42;
  res1[0]=w44;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #84: @44 = @44' */
  /* #85: {@12, @14, @16, @18, @20, @22, @24, @26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@44) */
  w12 = w44[0];
  w14 = w44[1];
  w16 = w44[2];
  w18 = w44[3];
  w20 = w44[4];
  w22 = w44[5];
  w24 = w44[6];
  w26 = w44[7];
  /* #86: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #87: @14 = (@14+@0) */
  w14 += w00;
  /* #88: output[0][1] = @14 */
  if (res[0]) res[0][1] = w14;
  /* #89: output[0][2] = @16 */
  if (res[0]) res[0][2] = w16;
  /* #90: @18 = (@18+@2) */
  w18 += w02;
  /* #91: output[0][3] = @18 */
  if (res[0]) res[0][3] = w18;
  /* #92: @18 = sin(@4) */
  w18 = sin( w04 );
  /* #93: @6 = (@6+@7) */
  w06 += w07;
  /* #94: @7 = 37.037 */
  w07 = 3.7037037037037038e+01;
  /* #95: @3 = (@7*@3) */
  w03  = (w07*w03);
  /* #96: @2 = (@6*@3) */
  w02  = (w06*w03);
  /* #97: @2 = (@18*@2) */
  w02  = (w18*w02);
  /* #98: @20 = (@20-@2) */
  w20 -= w02;
  /* #99: @4 = cos(@4) */
  w04 = cos( w04 );
  /* #100: @7 = (@7*@1) */
  w07 *= w01;
  /* #101: @6 = (@6*@7) */
  w06 *= w07;
  /* #102: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #103: @20 = (@20+@6) */
  w20 += w06;
  /* #104: output[0][4] = @20 */
  if (res[0]) res[0][4] = w20;
  /* #105: @22 = (@22+@5) */
  w22 += w05;
  /* #106: output[0][5] = @22 */
  if (res[0]) res[0][5] = w22;
  /* #107: @22 = 0.0397 */
  w22 = 3.9699999999999999e-02;
  /* #108: @5 = 71428.6 */
  w05 = 7.1428571428571435e+04;
  /* #109: @20 = 0.707107 */
  w20 = 7.0710678118654746e-01;
  /* #110: @20 = (@20*@10) */
  w20 *= w10;
  /* #111: @5 = (@5*@20) */
  w05 *= w20;
  /* #112: @22 = (@22*@5) */
  w22 *= w05;
  /* #113: @24 = (@24-@22) */
  w24 -= w22;
  /* #114: @4 = (@4*@3) */
  w04 *= w03;
  /* #115: @24 = (@24+@4) */
  w24 += w04;
  /* #116: @18 = (@18*@7) */
  w18 *= w07;
  /* #117: @24 = (@24+@18) */
  w24 += w18;
  /* #118: output[0][6] = @24 */
  if (res[0]) res[0][6] = w24;
  /* #119: @26 = (@26+@22) */
  w26 += w22;
  /* #120: @26 = (@26+@4) */
  w26 += w04;
  /* #121: @26 = (@26+@18) */
  w26 += w18;
  /* #122: output[0][7] = @26 */
  if (res[0]) res[0][7] = w26;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor2D_learned_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor2D_learned_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor2D_learned_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor2D_learned_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor2D_learned_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 44;
  if (sz_res) *sz_res = 41;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 129;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor2D_learned_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 44*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 41*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 129*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
